[Computer Architecture] 캐시 메모리.md
da-in/tech-interview-study pull request #133
Opened 2023-01-25 07:08 UTC by Lee-DoHa

## Summary

캐시메모리 입니당
## Check List

- [ ] I created file and check spell again
- [ ] I linked File to README.md

2023-01-25 07:34 UTC, da-in approved these changes

2023-01-25 07:37 UTC, da-in requested changes

2023-01-25 07:37 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +**캐시 미스 경우 3가지**
```suggestion
## 캐시 미스 경우 3가지
```

2023-01-25 07:37 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +**캐시 메모리 작동 원리**
가독성이 너무 떨어져서 제목 소제목 적용 부탁함다👍🙂
```suggestion
## 캐시 메모리 작동 원리
```

2023-01-25 07:37 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +구조 및 작동 방식
```suggestion
## 캐시 메모리 구조 및 작동 방식  
```

2023-01-25 07:48 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +
```suggestion
<br/>

```

2023-01-25 07:48 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +
```suggestion
<br/>

```

2023-01-25 07:48 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +
```suggestion
<br/>

```

2023-01-25 07:49 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +- Direct Mapped Cache
```suggestion
- **Direct Mapped Cache**
```

2023-01-25 07:50 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +- Fully Associative Cache
```suggestion
- **Fully Associative Cache**   
```

2023-01-25 07:50 UTC, da-in commented on Tech Interview Cheat Sheet/Computer Architecture/캐시 메모리.md
> +- Set Associative Cache
```suggestion
- **Set Associative Cache**   
```

2023-01-25 07:50 UTC, da-in approved these changes
하는 김에 몇개만 더.. 좋습니당🙂

2023-01-26 00:33 UTC, lalabulla approved these changes

2023-01-26 01:49 UTC, merged