[Network] TCP & UDP.md
da-in/tech-interview-study pull request #153
Opened 2023-09-04 10:26 UTC by lalabulla

## Summary

- TCP & UDP 개념 추가 보완

## Check List

- [x] I created file and check spell again
- [ ] I linked File to README.md

2023-09-05 19:39 UTC, kimgwon approved these changes

2023-09-07 04:15 UTC, da-in requested changes

2023-09-07 04:15 UTC, da-in commented on CS Deep Dive/Network/TCP & UDP.md
> +\**사탕 100개가 여러 번에 걸쳐서 옆사람에게 보내면 받는 사람은 사탕 100개가 쌓인 다음에 이를 한 번에 봉지에 담아 갈 수 있는 경우는 데이터의 경계가 없는 경우이다.*
```suggestion
\**데이터 경계 - 데이터를 보낼 때 여러번에 걸쳐 보낼 수 있는지의 여부 사탕 100개가 여러 번에 걸쳐서 옆사람에게 보내면 받는 사람은 사탕 100개가 쌓인 다음에 이를 한 번에 봉지에 담아 갈 수 있는 경우는 데이터의 경계가 없는 경우이다.*
```
- 데이터 경계에 대한 주석이므로 위와 같이 합쳐주면 좋을 것 같습니다. 
- 더불어 데이터 경계에 대한 설명이 부적절해보입니다. 실생활 예시보다는 좀더 구체적인 정의나 내용을 명시해주는 것 이 좋을 것 같습니다. 
- 다음 블로그를 참고하면 좋을 것 같습니다. https://rural-mouse.tistory.com/35

2023-09-07 04:15 UTC, da-in commented on CS Deep Dive/Network/TCP & UDP.md
> +\**가상 회선 방식 : TCP는 데이터를 전송하기 전에 각각의 기기마다 3-way Handshaking을 통해 논리적 연결을 수립하는데, 이를 가상 회선이라고 한다. (물리적인 연결은 아님을 주의하자)* </br>
```suggestion
\**가상 회선 방식 : TCP는 데이터를 전송하기 전에 각각의 기기마다 3-way Handshaking을 통해 논리적 연결을 수립하는데, 이를 가상 회선이라고 한다. (물리적인 연결은 아니다.)* </br>
```
- 종결어미 수정해주세용

2023-09-07 04:15 UTC, da-in commented on CS Deep Dive/Network/TCP & UDP.md
> +\**비연결형이기 때문에 할당되는 논리적인 경로가 없다. 따라서 각 패킷이 다른 경로로 전송되고, 독립적인 관계를 가진다. (순서대로 오는지 알 수 없다)*
이거는 어느 부분에 관한 주석이죠🧐

2023-09-07 04:15 UTC, da-in commented on CS Deep Dive/Network/TCP & UDP.md
> +\**세그먼트 : TCP 프로토콜에서의 데이터 단위*
세그먼트와 데이터그램에 대한 설명 맥락을 통일하면 좋을 것 같습니다. 세그먼트에 맞추면  
데이터그램 : UDP 프로토콜에서의 데이터단위  
가 될텐데, 이것보다 좀 더 유의미한 한 문장을 담으면 더 좋을 것 같구요.

2023-09-07 04:15 UTC, da-in commented on CS Deep Dive/Network/TCP & UDP.md
> +| 통신 | 일대일 통신 | 일대일, 일대다, 다대다 통신 |
```suggestion
|| TCP | UDP |
|-----|-----|-----|
| 연결 방식 | 연결형 프로토콜 | 비열결형 프로토콜 |
| 전송 순서 | 보장함 | 보장하지 않음 |
| 데이터 경계 | 구분함 | 구분하지 않음 |
| 신뢰성 | 신뢰성있는 데이터 전송 | 비신뢰성 데이터 전송 |
| 패킷 | 세그먼트| 데이터그램 |
| 전송 속도 | 느림 | 빠름 |
| 통신 | 1:1 | 1:1, 1:N, N:N |
```
뭔가 표가 정리된 느낌이 아니라서 우선 조금만 수정 했는데, 한 번 읽어보시고 더 개선해주세요

2023-09-07 04:15 UTC, da-in commented on CS Deep Dive/Network/TCP & UDP.md
> +- 패킷 손실 감지에 걸리는 시간 단축
```suggestion
- QUIC(Quick UDP Internet Connections)는 UDP를 기반으로 TCP + TLS + HTTP의 기능을 모두 구현하는 프로토콜이다.
- HTTP 3.0 부터는 TCP 대신 QUIC 프로토콜 채택하였다.
- QUIC은 TCP를 사용하지 않기 때문에 3 Way Handshake 과정을 거치지 않아도 된다.
- QUIC은 첫 연결 설정에 \*1 RTT만 소요된다. (TCP는 3 RTT 필요)
- 패킷 손실 감지에 걸리는 시간을 단축할 수 있다.
```
어조를 통일해주세요.

2023-09-07 06:53 UTC, da-in approved these changes

2023-09-07 06:53 UTC, da-in commented on CS Deep Dive/Network/TCP & UDP.md
> +### *데이터의 경계란?
```suggestion
### *데이터 경계
```
제목 수정합시당

2023-09-07 06:53 UTC, da-in commented on CS Deep Dive/Network/TCP & UDP.md
> +### *데이터의 경계란?
데이터 경계 설명 이미지 사이즈 수정하면 좋을 것 같습니다.  
저런 이미지는 이미지 내의 글씨가 본문 글씨보다 크지 않도록 줄여주는게 좋은 것 같아요.
LGTM! 👍🏻

2023-09-07 06:56 UTC, lalabulla commented on CS Deep Dive/Network/TCP & UDP.md
> +### *데이터의 경계란?
꼼꼼한 피드백 감사합니다-!🙌🏻

2023-09-11 03:20 UTC, merged