[Database] 정규화
da-in/tech-interview-study pull request #156
Opened 2023-09-04 14:53 UTC by jaminleee

## Summary

정규화 업데이트

## Check List

- [ ] I created file and check spell again
- [ ] I linked File to README.md

2023-09-05 19:39 UTC, kimgwon approved these changes

2023-09-06 15:59 UTC, lalabulla approved these changes

2023-09-07 04:22 UTC, da-in requested changes

2023-09-07 04:22 UTC, da-in commented on CS Deep Dive/Database/정규화.md
> +<details>
토글 사용은, 정말 부수적이면서 내용이 너무 길 때를 제외하고는 지양해주세요.

2023-09-07 04:22 UTC, da-in commented on CS Deep Dive/Database/정규화.md
>  - 이를 단계별로 구분하여 정규화 단계가 높아질수록 이상현상은 줄어들게 된다.
```suggestion
- 이를 단계별로 구분하여 정규화 단계가 높아질수록 [이상(Anomaly)](https://github.com/da-in/tech-interview-study/blob/main/CS%20Deep%20Dive/Database/%EC%9D%B4%EC%83%81_Anomaly.md)현상은 줄어들게 된다.
```
이상에 관한 내용은 다른 문서에서 다루고 있으므로 링크 걸어주시고, 아래의 Summary는 삭제해주세요. 기존 이상 관련 문서의 내용이 빈약하면, 해당 문서에 추가해주세용

2023-09-07 04:24 UTC, da-in commented
예시가 길어 가독성이 떨어지는 문제는 수정이 필요할 것 같습니다. 최후의 수단으로는 예시를 `summary tag` 로 감싸는 방법까지 고려해주세요.

2023-09-11 14:28 UTC, da-in commented on CS Deep Dive/Database/정규화.md
>  - 이를 단계별로 구분하여 정규화 단계가 높아질수록 이상현상은 줄어들게 된다.
@jaminleee Summary 내용이 다른 문서와 중복되어 불필요해보입니당. 용어도 다르구요 삭제하는 것이 좋을 것 같아요

2023-09-14 09:03 UTC, da-in approved these changes
LGTM 👍

2023-09-21 07:49 UTC, merged