데이터베이스 인덱스
da-in/tech-interview-study pull request #158
Opened 2023-09-11 07:39 UTC by chs98412

## Summary
데이터베이스 인덱스

## Check List

- [ ] I created file and check spell again 
다시 바꿔야할거 같아요 합칠지 새로운 이름으로 할지
- [ ] I linked File to README.md

2023-09-14 04:45 UTC, kimgwon approved these changes

2023-09-14 07:05 UTC, lalabulla requested changes
전체적으로 직관적인 사진이나 추가적인 보완 설명이 필요할 것 같아요

2023-09-14 07:05 UTC, lalabulla commented on CS Deep Dive/Database/인덱스(INDEX).md
> +리프노드에는 실제 데이터에 접근할 수 있도록 주솟값을 가지고 있게 된다.
어떤 주소 값인지 설명해주세요
추가로 직관적인 사진이나 예시가 있으면 좋을 것 같아요!

2023-09-14 07:05 UTC, lalabulla commented on CS Deep Dive/Database/인덱스(INDEX).md
> +주로 B-Tree 인덱스를 사용하게 되고 B-Tree 인덱스는 루트 노드, 브랜치 노드, 리프 노드로 이루어져 있다.
클러스터링 인덱스만 아니면 다 사용가능 한건가요?

2023-09-14 09:25 UTC, da-in commented
새로운 파일이 아닌, 기존 파일을 업데이트 해주세요!

2023-09-21 14:27 UTC, lalabulla approved these changes

2023-09-21 14:31 UTC, merged