[Networ] 대칭키 & 공개키
da-in/tech-interview-study pull request #161
Opened 2023-09-11 14:56 UTC by kimgwon

## Summary

## Check List

- [ ] I created file and check spell again
- [ ] I linked File to README.md

2023-09-14 06:42 UTC, lalabulla requested changes

2023-09-14 06:42 UTC, lalabulla commented on CS Deep Dive/Network/대칭키 & 공개키.md
> +3. 수신자는 암호문을 받아서 키와 복호화 알고리즘을 사용한다.
```suggestion
3. 수신자는 암호문을 받아서 동일한 키와 알고리즘을 사용하여 복호화한다.
```

2023-09-14 06:42 UTC, lalabulla commented on CS Deep Dive/Network/대칭키 & 공개키.md
> +  - 암호화 키(56bit)는 Round-key generator에 의해 각 라운드마다 서브키(48bit)를 생성하게 된다.
```suggestion
  - 암호화 키(56bit)는 Round-key generator에 의해 각 라운드마다 서로 다른 서브키(48bit)를 생성하게 된다.
```

2023-09-14 06:42 UTC, lalabulla commented on CS Deep Dive/Network/대칭키 & 공개키.md
> +  - 키의 길이는 달라도 라운드 키는 모두 128 bit이다.
라운드 키는 무엇이고 그냥 키는 무엇인가요?.?

2023-09-14 06:42 UTC, lalabulla commented on CS Deep Dive/Network/대칭키 & 공개키.md
> +공개키로 암호화 된 경우 개인키로만 해제를 할 수 있다.(공개키로 해제는 불가능하다.)
```suggestion
공개키로 암호화 된 경우 개인키로만 복호화를 할 수 있다.(공개키로 복호화는 불가능하다.)  
```

2023-09-14 06:42 UTC, lalabulla commented on CS Deep Dive/Network/대칭키 & 공개키.md
> +  - 송신자가 수신자에게 공개키를 요청하면, 수신자는 자신의 공개키를 송신자에게 전송한다. 송신자는 수신자로부터 받은 수신자의 공개키를 이용해 평문을 암호화 한 후 수신자에게 전송한다. 수신자는 개인키를 이용해 헤당 암호문을 복호화한다.
```suggestion
  - 송신자가 수신자에게 공개키를 요청하면, 수신자는 자신의 공개키를 송신자에게 전송한다. 송신자는 수신자로부터 받은 공개키를 이용해 평문을 암호화 한 후 수신자에게 전송한다. 
  - 수신자는 개인키를 이용해 헤당 암호문을 복호화한다.
```

2023-09-14 06:42 UTC, lalabulla commented on CS Deep Dive/Network/대칭키 & 공개키.md
> +  - 상대방의 공개키와 자신의 개인키를 이용하여 비밀키를 만들고, 서로 비밀키를 사용하여 데이터를 암호화하여 전달한다.
비밀키에 대한 설명이 조금 추가되면 좋을 거 같아요!.!

2023-09-14 09:12 UTC, da-in requested changes
문서의 몇몇 부분에서, 각 보안 방식이 '~를 중시한다' 라는 표현을 사용하는데 그 표현이 좀 어색한 것 같습니다. 사실 기밀성, 무결성 부인방지는 모두 중요한 게 맞고, 다른 것들은 경시 하는 것도 아니기에 다른 적절한 표현을 사용해야 할 것 같습니다.

제공한다, 보장한다 등의 표현도 사용되는 것 같고. 다른 문서들을 더 참고해주세요..

2023-09-14 09:12 UTC, da-in commented on CS Deep Dive/Network/대칭키 & 공개키.md
> -# 대칭키 & 공개키
`#`하나를 사용하여 문서의 제목을 표시해주세요.
추가로 제목을 변경한다면 파일 이름도 변경 부탁드립니당.

2023-09-14 09:25 UTC, da-in approved these changes
수정 후 머지해주세용 👍👍👍

2023-09-14 16:03 UTC, lalabulla approved these changes

2023-09-16 13:06 UTC, kimgwon commented on CS Deep Dive/Network/대칭키 & 공개키.md
> +  - 키의 길이는 달라도 라운드 키는 모두 128 bit이다.
_\*암호 키: 초기 비밀키_
_\*라운드 키: 특정 라운드에서 사용되는 키_

추가했습니다!

2023-09-16 13:08 UTC, merged